account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('customer/', views.create_customer_address_account, name='create-customer'),
    path('supplier/', views.create_supplier_address_account, name='create-supplier'),
    path('list/suppliers/', views.list_suppliers_view, name='list-suppliers'),
    path('list/customers/', views.list_customer_view, name='list-customers'),
    path('company/', views.create_company, name='create-company'),
    path('update/customer/<id>', views.update_customer_view, name='update-customer'),
    path('update/supplier/<id>', views.update_supplier_view, name='update-supplier'),
    path('delete/customer/<id>', views.delete_customer, name='delete-customer'),
    path('delete/supplier/<id>', views.delete_supplier, name='delete-supplier'),

]

alababak/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('account/', include('account.urls')),
                  path('inventory/', include('inventory.urls')),
                  path('orders/', include('orders.urls')),
                  path('locations/', include('location.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('en/', views.viewEN, name='en'),
    path('ar/', views.viewAR, name='ar'),
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('', views.homepage, name='homepage'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

account/models.py
from django.db import models
from django.conf import settings
from cities_light.models import Country,City

# Create your models here.
class Customer(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE, )
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    phone_number = models.CharField(max_length=30, blank=True, null=True)
    landline = models.CharField(max_length=30, blank=True, null=True)
    status = models.BooleanField(default=False, verbose_name='active', help_text='Checkbox if user is active')
    created_at = models.DateField(auto_now_add=True, null=True)
    last_updated_at = models.DateField(null=True,auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,
                                   related_name="customer_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Supplier(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE, )
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField()
    phone_number = models.CharField(max_length=30,blank=True, null=True)
    landline = models.CharField(max_length=30, blank=True, null=True)
    status = models.BooleanField(default=False,verbose_name='active', help_text='Checkbox if user is active')
    created_at = models.DateField(auto_now_add=True, null=True)
    last_updated_at = models.DateField(null=True,auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,
                                   related_name="supplier_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Address(models.Model):
    customer = models.ForeignKey('Customer', on_delete=models.CASCADE, blank=True, null=True)
    supplier = models.ForeignKey('Supplier', on_delete=models.CASCADE, blank=True, null=True)
    address = models.CharField(max_length=30, blank=True, null=True)
    country = models.ForeignKey(Country,on_delete=models.CASCADE, blank=True, null=True)
    city = models.CharField(max_length=30,blank=True, null=True)
    phone_number = models.CharField(max_length=30, blank=True, null=True)
    landline = models.CharField(max_length=30, blank=True, null=True)
    zip_code = models.CharField(max_length=30, null=True,blank=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    last_updated_at = models.DateField(null=True,auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,
                                   related_name="address_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name_plural = "Addresses"

    def __str__(self):
        return self.address


class Company(models.Model):
    name = models.CharField(max_length=30)
    created_at = models.DateField(auto_now_add=True, null=True)
    last_updated_at = models.DateField(null=True,auto_now=True, auto_now_add=False)
    created_by = models.IntegerField(null=True, blank=True)
    last_updated_by = models.IntegerField(null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Companies"

account/forms.py
from django import forms
from account.models import Customer, Supplier, Address, Company
from django.forms import inlineformset_factory


class CustomerCreationForm(forms.ModelForm):
    class Meta:
        model = Customer
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(CustomerCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class SupplierCreationForm(forms.ModelForm):
    class Meta:
        model = Supplier
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(SupplierCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class AddressCreationForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ('customer', 'supplier', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')
    def __init__(self, *args, **kwargs):
        super(AddressCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class CompanyCreationForm(forms.ModelForm):
    class Meta:
        model = Company
        exclude = ('created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(CompanyCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


customer_address_formset = inlineformset_factory(Customer, Address, form=AddressCreationForm, extra=3, can_delete=False)
supplier_address_formset = inlineformset_factory(Supplier, Address, form=AddressCreationForm, extra=3, can_delete=False)

account/views.py
from django.shortcuts import render, redirect
from account.forms import (CustomerCreationForm, SupplierCreationForm, customer_address_formset,
                           supplier_address_formset, CompanyCreationForm, )
from account.models import Customer, Supplier
from django.contrib import messages


def create_customer_address_account(request):
    if request.method == 'POST':
        customer_form = CustomerCreationForm(request.POST)
        address_inlineformset = customer_address_formset(request.POST)
        if customer_form.is_valid() and address_inlineformset.is_valid():
            customer_obj = customer_form.save(commit=False)
            customer_obj.created_by = request.user
            customer_obj.company = request.user.company
            customer_obj.save()
            address_inlineformset = customer_address_formset(request.POST, instance=customer_obj)
            if address_inlineformset.is_valid():
                address_obj = address_inlineformset.save(commit=False)
                for address in address_obj:
                    address.created_by = request.user
                    address.save()

                messages.success(request, 'Saved Successfully')
                return redirect('account:list-customers')
            else:
                print(address_inlineformset.errors)
        else:
            print(customer_form.errors)
    else:
        customer_form = CustomerCreationForm()
        address_inlineformset = customer_address_formset()

    customer_information_context = {
        'account_form': customer_form,
        'address_inlineformset': address_inlineformset,
        'title':'New Customer'
    }
    return render(request, 'create-supplier.html', context=customer_information_context)


def create_supplier_address_account(request):
    if request.method == 'POST':
        supplier_form = SupplierCreationForm(request.POST)
        address_inlineformset = supplier_address_formset(request.POST)
        if supplier_form.is_valid() and address_inlineformset.is_valid():
            supplier_obj = supplier_form.save(commit=False)
            supplier_obj.created_by = request.user
            supplier_obj.company = request.user.company
            supplier_obj.save()
            address_inlineformset = supplier_address_formset(request.POST, instance=supplier_obj)
            if address_inlineformset.is_valid():
                address_obj = address_inlineformset.save(commit=False)
                for address in address_obj:
                    address.created_by = request.user
                    address.save()

                messages.success(request, 'Saved Successfully')
                return redirect('account:list-suppliers')
            else:
                print(address_inlineformset.errors)
        else:
            print(supplier_form.errors)
    else:
        supplier_form = SupplierCreationForm()
        address_inlineformset = supplier_address_formset()

    supplier_information_context = {
        'account_form': supplier_form,
        'address_inlineformset': address_inlineformset,
        'title':'New Supplier'

    }

    return render(request, 'create-supplier.html', context=supplier_information_context)


def create_company(request):
    form = CompanyCreationForm()
    if request.method == 'POST':
        form = CompanyCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home:homepage')
    req_form = {'company_form': form}
    return render(request, 'create-company.html', context=req_form)


def list_customers(request):
    customers = Customer.objects.all().values()
    supcontext = {'dict_customers': customers}
    return render(request, 'list_customers.html', context=supcontext)


def list_suppliers(request):
    suppliers = Supplier.objects.all().values()
    supcontext = {'dict_suppliers': suppliers}
    return render(request, 'list_suppliers.html', context=supcontext)


def list_suppliers_view(request):
    supliers_list = Supplier.objects.all()
    supContext = {
        'supliers_list': supliers_list,
    }
    return render(request, 'list-suppliers.html', supContext)


def list_customer_view(request):
    customers_list = Customer.objects.all()
    supContext = {
        'customers_list': customers_list,
    }
    return render(request, 'list-customers.html', supContext)


def update_customer_view(request, id):
    customer = Customer.objects.get(pk=id)
    customer_form = CustomerCreationForm(instance=customer)
    address_inlineformset = customer_address_formset(instance=customer)
    if request.method == 'POST':
        customer_form = CustomerCreationForm(request.POST, instance=customer)
        address_inlineformset = customer_address_formset(request.POST, instance=customer)
        if customer_form.is_valid() and address_inlineformset.is_valid():
            customer_obj = customer_form.save(commit=False)
            customer_obj.last_updated_by = request.user
            customer_obj.save()
            address_inlineformset = customer_address_formset(request.POST, instance=customer_obj)
            if address_inlineformset.is_valid():
                address_obj = address_inlineformset.save(commit=False)
                for address in address_obj:
                    address.last_updated_by = request.user
                    address.save()
                messages.success(request, 'Saved Successfully')
                return redirect('account:list-customers')
            else:
                print(address_inlineformset.errors)
        else:
            print(customer_form.errors)

    supContext = {
        'account_form': customer_form,
        'address_inlineformset': address_inlineformset,
        'title': 'Update Customer'

    }
    return render(request, 'create-supplier.html', supContext)


def update_supplier_view(request, id):
    supplier = Supplier.objects.get(pk=id)
    supplier_form = SupplierCreationForm(instance=supplier)
    address_inlineformset = supplier_address_formset(instance=supplier)
    if request.method == 'POST':
        supplier_form = SupplierCreationForm(request.POST, instance=supplier)
        address_inlineformset = supplier_address_formset(request.POST, instance=supplier)
        if supplier_form.is_valid() and address_inlineformset.is_valid():
            supplier_obj = supplier_form.save(commit=False)
            supplier_obj.last_updated_by = request.user
            supplier_obj.save()
            address_inlineformset = supplier_address_formset(request.POST, instance=supplier_obj)
            if address_inlineformset.is_valid():
                address_obj = address_inlineformset.save(commit = False)
                for address in address_obj:
                    address.last_updated_by = request.user
                    address.save()
                messages.success(request, 'Saved Successfully')
                return redirect('account:list-suppliers')

            else:
                print(address_inlineformset.errors)
        else:
            print(supplier_form.errors)

    supContext = {
        'account_form': supplier_form,
        'address_inlineformset': address_inlineformset,
        'title': 'Update Supplier'

    }
    return render(request, 'create-supplier.html', supContext)


def delete_customer(request, id):
    customer = Customer.objects.get(pk=id)
    deleted = customer.delete()
    if deleted:
        return redirect('account:list-customers')
    else:
        print("item not deleted")


def delete_supplier(request, id):
    supplier = Supplier.objects.get(pk=id)
    deleted = supplier.delete()
    if deleted:
        return redirect('account:list-suppliers')
    else:
        print("item not deleted")

account/templates/create-company.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Datatables Default</h1>
      <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
        <ol class="breadcrumb pt-0">
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">Library</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Data</li>
        </ol>
      </nav>
   </div>

  </div>
  <div class="card mb-4">
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
               <label>Company Name</label>
               {{company_form.name}}
          </div>
        </div>
        <button type="submit" class="btn btn-primary d-block mt-3">Save</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

account/templates/create-supplier.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>{{title}}</h1>
      <div class="text-zero top-right-button-container">
        <a href="{% url 'account:list-suppliers'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">BACK TO LIST</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-body">

      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>First Name</label>
            {{account_form.first_name}}
          </div>
          <div class="form-group col-md-6">
            <label>Last Name</label>
            {{account_form.last_name}}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-4">
            <label>Email</label>
            {{account_form.email}}
          </div>
          <div class="form-group col-md-4">
            <label>Mobile</label>
            {{account_form.phone_number}}
          </div>
          <div class="form-group col-md-4">
            <label>Land line</label>
            {{account_form.landline}}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-2">
            {{account_form.status}}
            <label>Active</label>
          </div>
        </div>
        <!-- Address part  -->
        <table class="data-table data-table-scrollable responsive nowrap dataTable no-footer dtr-inline">
          {{ address_inlineformset.management_form }}
          {% for form in address_inlineformset %}
          {{ form.id }}
          {% if forloop.first %}
          <thead>
            <tr>
              {% for field in form.visible_fields %}
              <th>{{ field.label|capfirst }}</th>
              {% endfor %}
            </tr>
          </thead>
          {% endif %}
          <tr>
            {% for field in form.visible_fields %}
            <td>
              {# exclude the hidden fields in the form #}
              {% if forloop.first %}
              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
              {% endif %}
              {{ field.errors.as_ul }}
              {{ field }}
            </td>
            {% endfor %}
          </tr>
          {% endfor %}
        </table>
        <button type="submit" class="btn btn-primary d-block mt-3">Save</button>
      </form>
    </div>
  </div>


</div>

{% endblock %}

account/templates/list-customers.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Customers</h1>
      <div class="text-zero top-right-button-container">
        <a href="{% url 'account:create-customer'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">ADD NEW</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature6 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending">Customer ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "First Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Last Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Email" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Phone" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for customer in customers_list %}
                <tr role="row" class="odd">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ customer.first_name }}</td>
                  <td>{{ customer.last_name }}</td>
                  <td>{{ customer.email }}</td>
                  <td>{{ customer.phone_number }}</td>
                  <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="{% url 'account:update-customer' id=customer.id %}">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete-modal{{customer.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <div class="modal fade" id="delete-modal{{customer.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="{% url 'account:delete-customer' id=customer.pk %}" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}

account/templates/list-suppliers.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Suppliers</h1>
      <div class="text-zero top-right-button-container">
        <a href="{% url 'account:create-supplier'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">ADD NEW</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature6 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending">Supplier ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "First Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Last Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Email" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Phone" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for supplier in supliers_list %}
                <tr role="row" class="odd">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ supplier.first_name }}</td>
                  <td>{{ supplier.last_name }}</td>
                  <td>{{ supplier.email }}</td>
                  <td>{{ supplier.phone_number }}</td>
                  <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="{% url 'account:update-supplier' id=supplier.id %}">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete-modal{{supplier.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <div class="modal fade" id="delete-modal{{supplier.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="{% url 'account:delete-supplier' id=supplier.pk %}" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}