alababak/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('account/', include('account.urls')),
                  path('inventory/', include('inventory.urls')),
                  path('orders/', include('orders.urls')),
                  path('locations/', include('location.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('en/', views.viewEN, name='en'),
    path('ar/', views.viewAR, name='ar'),
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('', views.homepage, name='homepage'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('purchase/', views.create_purchase_order_view, name='create-po'),
    path('list/purchase-orders/', views.list_purchase_order_view, name='list-po'),
    path('update/purchase-order/<id>', views.update_purchase_order_view, name='update-po'),
    path('delete/purchase-order/<id>', views.delete_purchase_order_view, name='delete-po'),
    path('sale/', views.create_sales_order_view, name='create-so'),
    path('list/sale-orders/', views.list_sale_order_view, name='list-so'),
    path('update/sale-order/<id>', views.update_sale_order_view, name='update-so'),
    path('delete/sale-order/<id>', views.delete_sale_order_view, name='delete-so'),

]

orders/models.py
from django.db import models
from djmoney.models.fields import MoneyField
from account.models import Supplier, Customer, Company
from inventory.models import Item
from django.conf import settings


# Create your models here.
class PurchaseOder(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    supplier = models.ForeignKey(Supplier, on_delete=models.CASCADE, )
    code = models.CharField(max_length=10)
    total_price = MoneyField(max_digits=14, decimal_places=2, default_currency='EGP', null=True, blank=True)
    status = models.CharField(max_length=8,
                              choices=[('received', 'Received'), ('returned', 'Returned'), ('shipping', 'Shipping')])
    date = models.DateField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    last_updated_at = models.DateField(null=True, auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,
                                   related_name="purchase_order_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.code


class SalesOrder(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, )
    code = models.CharField(max_length=10)
    total_price = MoneyField(max_digits=14, decimal_places=2, default_currency='EGP')
    status = models.CharField(max_length=8,
                              choices=[('received', 'Received'), ('returned', 'Returned'), ('shipping', 'Shipping')])
    date = models.DateField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True, null=True)
    # date = models.DateField()
    last_updated_at = models.DateField(null=True, auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,
                                   related_name="sale_order_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.code


class PurchaseTransaction(models.Model):
    purchase_order = models.ForeignKey(PurchaseOder, on_delete=models.CASCADE, )
    item = models.ForeignKey(Item, on_delete=models.CASCADE, )
    quantity = models.IntegerField()
    total_price = MoneyField(max_digits=14, decimal_places=2, default_currency='EGP')
    created_at = models.DateField(auto_now_add=True, null=True)
    last_updated_at = models.DateField(null=True, auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,
                                   related_name="purchase_transation_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)


def __str__(self):
    return self.purchase_order.code + " Transaction"


class SalesTransaction(models.Model):
    sales_order = models.ForeignKey(SalesOrder, on_delete=models.CASCADE, )
    item = models.ForeignKey(Item, on_delete=models.CASCADE, )
    quantity = models.IntegerField()
    total_price = MoneyField(max_digits=14, decimal_places=2, default_currency='EGP')
    created_at = models.DateField(auto_now_add=True, null=True)
    last_updated_at = models.DateField(null=True, auto_now=True, auto_now_add=False)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True,
                                   related_name="sale_transaction_created_by")
    last_updated_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.sales_order.code + " Transaction"

orders/forms.py
from django import forms
from orders.models import PurchaseOder
from django.forms import inlineformset_factory
from orders.models import PurchaseOder, PurchaseTransaction, SalesOrder, SalesTransaction
from djmoney.models.fields import MoneyField


class PurchaseOrderCreationForm(forms.ModelForm):
    class Meta:
        model = PurchaseOder
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control tm', 'type': 'date', })
        }

    def __init__(self, *args, **kwargs):
        super(PurchaseOrderCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'total_price':
                self.fields[field].widget.attrs['class'] = 'form-control'

            elif self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class PurchaseTransactionCreationForm(forms.ModelForm):
    class Meta:
        model = PurchaseOder
        exclude = ('created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(PurchaseTransactionCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'total_price':
                self.fields[field].widget.attrs['class'] = 'form-control'

            elif self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class SaleOrderCreationForm(forms.ModelForm):
    class Meta:
        model = SalesOrder
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control tm', 'type': 'date', })
        }

    def __init__(self, *args, **kwargs):
        super(SaleOrderCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'total_price':
                self.fields[field].widget.attrs['class'] = 'form-control'

            elif self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class SaleTransactionCreationForm(forms.ModelForm):
    class Meta:
        model = SalesTransaction
        exclude = ('created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(SaleTransactionCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if field == 'total_price':
                self.fields[field].widget.attrs['class'] = 'form-control'

            elif self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


purchase_transaction_formset = inlineformset_factory(PurchaseOder, PurchaseTransaction,
                                                     form=PurchaseTransactionCreationForm, extra=3, can_delete=False)

sale_transaction_formset = inlineformset_factory(SalesOrder, SalesTransaction,
                                                 form=SaleTransactionCreationForm, extra=3, can_delete=False)

orders/views.py
from django.shortcuts import render, redirect
from orders.forms import PurchaseOrderCreationForm, purchase_transaction_formset, sale_transaction_formset, \
    SaleOrderCreationForm
from orders.models import PurchaseOder, SalesOrder
from django.contrib import messages


# Create your views here.
def create_purchase_order_view(request):
    po_form = PurchaseOrderCreationForm()
    po_transaction_inlineformset = purchase_transaction_formset()
    if request.method == 'POST':
        po_form = PurchaseOrderCreationForm(request.POST)
        po_transaction_inlineformset = purchase_transaction_formset(request.POST)
        if po_form.is_valid() and po_transaction_inlineformset.is_valid():
            po_obj = po_form.save(commit=False)
            po_obj.created_by = request.user
            po_obj.company = request.user.company
            po_instance = po_obj.save()
            po_transaction_inlineformset = purchase_transaction_formset(request.POST, instance=po_instance)
            if po_transaction_inlineformset.is_valid():
                po_transaction_obj = po_transaction_inlineformset.save(commit=False)
                for po_transaction in po_transaction_obj:
                    po_transaction.created_by = request.user
                    po_transaction.save()
                messages.success(request, 'Saved Successfully')
                return redirect('orders:list-po')
            else:
                print(po_transaction_inlineformset.errors)
        else:
            print(po_form.errors)
    subcontext = {
        'po_form': po_form,
        'po_transaction_inlineformset': po_transaction_inlineformset,
        'title':'New Purchase Order'
    }
    return render(request, 'create-purchase-order.html', context=subcontext)


def list_purchase_order_view(request):
    purchase_orders = PurchaseOder.objects.all()
    subcontext = {
        'purchase_orders_list': purchase_orders
    }
    return render(request, 'list-purchase_orders.html', context=subcontext)


def update_purchase_order_view(request, id):
    order = PurchaseOder.objects.get(pk=id)
    purchase_order_form = PurchaseOrderCreationForm(instance=order)
    po_transaction_inlineformset = purchase_transaction_formset(instance=order)
    if request.method == 'POST':
        purchase_order_form = PurchaseOrderCreationForm(request.POST, instance=order)
        po_transaction_inlineformset = purchase_transaction_formset(request.POST, instance=order)
        if purchase_order_form.is_valid() and po_transaction_inlineformset.is_valid():
            po_obj = purchase_order_form.save(commit=False)
            po_obj.last_updated_by = request.user
            po_instance = po_obj.save()
            po_transaction_inlineformset = purchase_transaction_formset(request.POST, instance=po_instance)
            if po_transaction_inlineformset.is_valid():
                po_transaction_obj = po_transaction_inlineformset.save(commit=False)
                for po_transaction in po_transaction_obj:
                    po_transaction.last_updated_by = request.user
                    po_transaction.save()
                messages.success(request, 'Saved Successfully')
                return redirect('orders:list-po')
            else:
                print(po_transaction_inlineformset.errors)
        else:
            print(purchase_order_form.errors)

    supContext = {
        'po_form': purchase_order_form,
        'po_transaction_inlineformset': po_transaction_inlineformset,
        'title': 'Update Purchase Order'

    }
    return render(request, 'create-purchase-order.html', supContext)


def delete_purchase_order_view(request, id):
    po_order = PurchaseOder.objects.get(pk=id)
    deleted = po_order.delete()
    if deleted:
        return redirect('orders:list-po')
    else:
        print("item not deleted")


def create_sales_order_view(request):
    so_form = SaleOrderCreationForm()
    so_transaction_inlineformset = sale_transaction_formset()
    if request.method == 'POST':
        so_form = SaleOrderCreationForm(request.POST)
        so_transaction_inlineformset = sale_transaction_formset(request.POST)
        if so_form.is_valid() and so_transaction_inlineformset.is_valid():
            so_obj = so_form.save(commit=False)
            so_obj.created_by = request.user
            so_obj.company = request.user.company
            so_instance = so_obj.save()
            so_transaction_inlineformset = sale_transaction_formset(request.POST, instance=so_instance)
            if so_transaction_inlineformset.is_valid():
                so_transaction_obj = so_transaction_inlineformset.save(commit=False)
                for so_transaction in so_transaction_obj:
                    so_transaction.created_by = request.user
                    so_transaction.save()
                messages.success(request, 'Saved Successfully')
                return redirect('orders:list-so')
            else:
                print(so_transaction_inlineformset.errors)
        else:
            print(so_form.errors)
    subcontext = {
        'so_form': so_form,
        'so_transaction_inlineformset': so_transaction_inlineformset,
        'title': 'New Sale Order'

    }
    return render(request, 'create-sale-order.html', context=subcontext)


def list_sale_order_view(request):
    sale_orders = SalesOrder.objects.all()
    subcontext = {
        'sale_orders_list': sale_orders
    }
    return render(request, 'list-sale_orders.html', context=subcontext)


def update_sale_order_view(request, id):
    order = SalesOrder.objects.get(pk=id)
    sale_order_form = SaleOrderCreationForm(instance=order)
    so_transaction_inlineformset = sale_transaction_formset(instance=order)
    if request.method == 'POST':
        sale_order_form = SaleOrderCreationForm(request.POST, instance=order)
        so_transaction_inlineformset = sale_transaction_formset(request.POST, instance=order)
        if sale_order_form.is_valid() and so_transaction_inlineformset.is_valid():
            so_obj = sale_order_form.save(commit=False)
            so_obj.last_updated_by = request.user
            so_instance = so_obj.save()
            so_transaction_inlineformset = sale_transaction_formset(request.POST, instance=so_instance)
            if so_transaction_inlineformset.is_valid():
                so_transaction_obj = so_transaction_inlineformset.save(commit=False)
                for so_transaction in so_transaction_obj:
                    so_transaction.last_updated_by = request.user
                    so_transaction.save()
                messages.success(request, 'Saved Successfully')
                return redirect('orders:list-so')
            else:
                print(so_transaction_inlineformset.errors)
        else:
            print(sale_order_form.errors)

    supContext = {
        'so_form': sale_order_form,
        'so_transaction_inlineformset': so_transaction_inlineformset,
        'title': 'Update Sale Order'

    }
    return render(request, 'create-sale-order.html', supContext)


def delete_sale_order_view(request, id):
    so_order = SalesOrder.objects.get(pk=id)
    deleted = so_order.delete()
    if deleted:
        return redirect('orders:list-so')
    else:
        print("item not deleted")

orders/templates/create-po.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Datatables Default</h1>
      <nav class="breadcrumb-container d-none d-sm-block d-lg-inline-block" aria-label="breadcrumb">
        <ol class="breadcrumb pt-0">
          <li class="breadcrumb-item">
            <a href="#">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="#">Library</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Data</li>
        </ol>
      </nav>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-body">

      <form method="POST">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label>Supplier</label>
              {{po_form.supplier}}
          </div>
          <div class="form-group col-md-6">
            <label>code</label>
              {{po_form.code}}
          </div>
          <div class="form-group col-md-6">
            <label>total_price</label>
              {{po_form.total_price}}
          </div>
          <div class="form-group col-md-6">
            <label>status</label>
              {{po_form.status}}
          </div>
        </div>

        <table style = "width:100%">
                {{ po_transaction_inlineformset.management_form }}
                {% for form in po_transaction_inlineformset %}
                {{ form.id }}
                {% if forloop.first %}
                <thead>
                  <tr>
                    {% for field in form.visible_fields %}
                    <th>{{ field.label|capfirst }}</th>
                    {% endfor %}
                  </tr>
                </thead>
                {% endif %}
                <tr>
                  {% for field in form.visible_fields %}
                  <td>
                    {# exclude the hidden fields in the form #}
                    {% if forloop.first %}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    {% endif %}
                    {{ field.errors.as_ul }}
                    {{ field }}
                  </td>
                  {% endfor %}
                </tr>
                {% endfor %}
              </table>
        <button type="submit" class="btn btn-primary d-block mt-3">Save</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/list-purchase_orders.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Purchase Orders</h1>

      <div class="text-zero top-right-button-container">
        <a href="{% url 'orders:create-po'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">ADD NEW</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature6 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 155.4px;">Order ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 263.4px;">{% trans "Code" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 105.8px;">{% trans "Supplier" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 61.8px;">{% trans "Total Price" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 122.6px;">{% trans "Status" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 86.6px;">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for order in purchase_orders_list %}
                <tr role="row" class="odd">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ order.code }}</td>
                  <td>{{ order.supplier }}</td>
                  <td>{{ order.total_price }}</td>
                  <td>{{ order.status }}</td>
                  <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="{% url 'orders:update-po' id=order.pk %}">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="{% url 'orders:delete-po' id=order.pk %}" data-toggle="modal" data-target="#delete-modal{{order.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <!-- Delete Modal -->
                <div class="modal fade" id="delete-modal{{order.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="{% url 'orders:delete-po' id=order.pk %}" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}

orders/templates/list-sale_orders.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Sale Orders</h1>

      <div class="text-zero top-right-button-container">
        <a href="{% url 'orders:create-so'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">ADD NEW</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col-12 mb-4">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature6 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 155.4px;">Order ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Position: activate to sort column ascending" style="width: 263.4px;">{% trans "Code" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Office: activate to sort column ascending" style="width: 105.8px;">{% trans "Customer" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Age: activate to sort column ascending" style="width: 61.8px;">{% trans "Total Price" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Start date: activate to sort column ascending" style="width: 122.6px;">{% trans "Status" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Salary: activate to sort column ascending" style="width: 86.6px;">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for order in sale_orders_list %}
                <tr role="row" class="odd">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ order.code }}</td>
                  <td>{{ order.customer }}</td>
                  <td>{{ order.total_price }}</td>
                  <td>{{ order.status }}</td>
                   <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="{% url 'orders:update-so' id=order.pk %}">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="{% url 'orders:delete-so' id=order.pk %}" data-toggle="modal" data-target="#delete-modal{{order.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <!-- Delete Modal -->
                <div class="modal fade" id="delete-modal{{order.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="{% url 'orders:delete-so' id=order.pk %}" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}