account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('customer/', views.create_customer_address_account, name='create-customer'),
    path('supplier/', views.create_supplier_address_account, name='create-supplier'),
    path('list/suppliers/', views.list_suppliers_view, name='list-suppliers'),
    path('list/customers/', views.list_customer_view, name='list-customers'),
    path('company/', views.create_company, name='create-company'),
    path('update/customer/<id>', views.update_customer_view, name='update-customer'),
    path('update/supplier/<id>', views.update_supplier_view, name='update-supplier'),
    path('delete/customer/<id>', views.delete_customer, name='delete-customer'),
    path('delete/supplier/<id>', views.delete_supplier, name='delete-supplier'),

]

alababak/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('account/', include('account.urls')),
                  path('inventory/', include('inventory.urls')),
                  path('orders/', include('orders.urls')),
                  path('locations/', include('location.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('en/', views.viewEN, name='en'),
    path('ar/', views.viewAR, name='ar'),
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('', views.homepage, name='homepage'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

inventory/urls.py
from django.urls import path
from inventory import views

app_name = 'inventory'
urlpatterns = [
               path('category/list/', views.list_categorires_view, name='list-categories'),
               path('category/create/', views.create_category_view, name='create-category'),
               path('brands/list/', views.list_brands_view, name='list-brands'),
               path('brand/create/', views.create_brand_view, name='create-brand'),
               path('attribute/list/', views.list_attributes_view, name='list-attributes'),
               path('attribute/create/', views.create_attribute_view, name='create-attribute'),
               path('product/list/', views.list_products_view, name='list-products'),
               path('product/create/', views.create_product_item_view, name='create-product'),
               path('stoke/list/', views.list_stoketake_view, name='list-stokes'),
               path('stoke/create/', views.create_stoketake_view, name='create-stoke'),
               path('uom/create/', views.create_uom_view, name='create-uom'),
               path('uom/list/', views.list_uom_view, name='list-uom'),

]

location/urls.py
from django.urls import path
from location import views

app_name = 'location'

urlpatterns = [
    path('create/', views.create_location_view, name='create-location'),
    path('update/', views.update_location_view, name='update-location'),
    path('list/locations/', views.list_location_view, name='list-locations'),
    path('delete/', views.delete_location_view, name='delete-location'),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'
urlpatterns = [
    path('purchase/', views.create_purchase_order_view, name='create-po'),
    path('list/purchase-orders/', views.list_purchase_order_view, name='list-po'),
    path('update/purchase-order/<id>', views.update_purchase_order_view, name='update-po'),
    path('delete/purchase-order/<id>', views.delete_purchase_order_view, name='delete-po'),
    path('sale/', views.create_sales_order_view, name='create-so'),
    path('list/sale-orders/', views.list_sale_order_view, name='list-so'),
    path('update/sale-order/<id>', views.update_sale_order_view, name='update-so'),
    path('delete/sale-order/<id>', views.delete_sale_order_view, name='delete-so'),

]

alababak/templates/footer.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<div class="footer-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-sm-6">
              <span>Copyright © 2019 3alababak. All rights reserved.</span>
                <p class="mb-0 text-muted">ColoredStrategies 2019</p>
            </div>
            
        </div>
    </div>
</div>

alababak/templates/login.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<html {% if LANGUAGE_BIDI %} dir="rtl" {% else %} dir="ltr" {% endif %}>

<head>
  <meta charset="UTF-8">
  <title>3alababak Login</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <link rel="stylesheet" href="{% static 'src/font/iconsmind-s/css/iconsminds.css' %}" />
  <link rel="stylesheet" href="{% static 'src/font/simple-line-icons/css/simple-line-icons.css' %}" />

  <link rel="stylesheet" href="{% static 'src/css/vendor/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'src/css/vendor/bootstrap.rtl.only.min.css' %}" />
  <link rel="stylesheet" href="{% static 'src/css/vendor/bootstrap-float-label.min.css' %}" />
  <link rel="stylesheet" href="{% static 'src/css/main.css' %}" />
  <link rel="stylesheet" href="{% static "src/css/dore.light.bluenavy.min.css" %}" />
</head>

<body class="background show-spinner no-footer">
  <div class="fixed-background"></div>
  <main>
    <div class="container">
      <div class="row h-100">
        <div class="col-12 col-md-10 mx-auto my-auto">
          <div class="card auth-card">
            <div class="position-relative image-side ">
              <p class=" text-white h2">MAGIC IS IN THE DETAILS</p>
              <p class="white mb-0">
                Please use your credentials to login.
                <br>If you are not a member, please
                <a href="{% url 'home:register'%}" class="white">register</a>.
              </p>
            </div>
            <div class="form-side">
              <a href="#">
                <img src="{% static 'src/logos/Logo3alababak.svg' %}" alt="">
              </a>
              <h6 class="mb-4">Login</h6>
              <form method="POST">
                {% csrf_token %}
                <label class="form-group has-float-label mb-4">
                  <input class="form-control" name="username" />
                  <span>Username</span>
                </label>

                <label class="form-group has-float-label mb-4">
                  <input class="form-control" name="password" type="password" placeholder="" />
                  <span>Password</span>
                </label>
                <div class="d-flex justify-content-between align-items-center">
                  <a href="{% url 'home:register'%}">Don't have account</a>
                  <button class="btn btn-primary btn-lg btn-shadow" type="submit">LOGIN</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
  <script src="{% static 'src/js/vendor/jquery-3.3.1.min.js'%}"></script>
  <script src="{% static 'src/js/vendor/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'src/js/dore.script.js'%}"></script>
  <script src="{% static "src/js/dore.script.js" %}"></script>
  <script src="{% static "src/js/scripts.single.theme.js" %}"></script>
</body>

</html>

alababak/templates/master.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<html {% if LANGUAGE_BIDI %} dir="rtl" {% else %} dir="ltr" {% endif %}>

<head>
  <meta charset="UTF-8">
  <title>3alababak</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="icon" type="image/png" href="{% static "src/logos/3alababak_icon.png"%}">
  <link rel="stylesheet" href="{% static "src/font/iconsmind-s/css/iconsminds.css" %}" />
  <link rel="stylesheet" href="{% static "src/font/simple-line-icons/css/simple-line-icons.css" %}" />

  <link rel="stylesheet" href="{% static "src/css/vendor/bootstrap.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/bootstrap.rtl.only.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/fullcalendar.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/dataTables.bootstrap4.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/datatables.responsive.bootstrap4.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/select2.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/perfect-scrollbar.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/glide.core.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/bootstrap-stars.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/nouislider.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/bootstrap-datepicker3.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/vendor/component-custom-switch.min.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/main.css" %}" />
  <link rel="stylesheet" href="{% static "src/css/dore.light.redruby.min.css" %}" />


</head>

<body id="app-container" class="menu-default show-spinner">

  <nav class="navbar fixed-top">
    {% include 'top-nav.html' %}
  </nav>
  <div class="menu">
    {% include 'side-bar.html' %}
  </div>

  <main>

    <div class="container-fluid">
      {% block body %}
      {% endblock body %}
    </div>
  </main>

  <footer class="page-footer">
    {% include 'footer.html' %}
  </footer>


  <script src="{% static "src/js/vendor/jquery-3.3.1.min.js" %}"></script>
  <script src="{% static "src/js/vendor/bootstrap.bundle.min.js" %}"></script>
  <script src="{% static "src/js/vendor/Chart.bundle.min.js" %}"></script>
  <script src="{% static "src/js/vendor/chartjs-plugin-datalabels.js" %}"></script>
  <script src="{% static "src/js/vendor/moment.min.js" %}"></script>
  <script src="{% static "src/js/vendor/fullcalendar.min.js" %}"></script>
  <script src="{% static "src/js/vendor/datatables.min.js" %}"></script>
  <script src="{% static "src/js/vendor/perfect-scrollbar.min.js" %}"></script>
  <script src="{% static "src/js/vendor/progressbar.min.js" %}"></script>
  <script src="{% static "src/js/vendor/jquery.barrating.min.js" %}"></script>
  <script src="{% static "src/js/vendor/select2.full.js" %}"></script>
  <script src="{% static "src/js/vendor/nouislider.min.js" %}"></script>
  <script src="{% static "src/js/vendor/bootstrap-datepicker.js" %}"></script>
  <script src="{% static "src/js/vendor/Sortable.js" %}"></script>
  <script src="{% static "src/js/vendor/mousetrap.min.js" %}"></script>
  <script src="{% static "src/js/vendor/glide.min.js" %}"></script>

  <script src="{% static "src/js/dore.script.js" %}"></script>
  <script src="{% static "src/js/scripts.single.theme.js" %}"></script>

  <script type="text/javascript">
    $(".color").click(function() { //toggleClass
      if ($(this).hasClass("active")) {
        console.log('clicked');
        //$(this).addClass("active");
        $(this).removeClass("active");
      } else {
        console.log('testclicked');
        $(this).addClass("active");
      }
      localStorage.setItem("active", $(this).parent().index());
      localStorage.setItem("activec", $(this).index());
      console.log('testclickeding' + $(this).parent().index() + $(this).index());

    });

    var ele = localStorage.getItem("active");
    var ele1 = localStorage.getItem("activec");
    //$('ul li:eq(' + ele1 + ')').find('a').addClass("active");
    $('ul li:eq(' + ele1 + ')').find('a').addClass("active");
    $('ul li:eq(' + ele + ')').addClass("active");
    console.log('testclicked' + ele + ele1);
  </script>
  {% block js %}{% endblock js %}
</body>

</html>

alababak/templates/register.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title></title>
  <title>3alababak</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <link rel="stylesheet" href="{% static 'src/font/iconsmind-s/css/iconsminds.css' %}" />
  <link rel="stylesheet" href="{% static 'src/font/simple-line-icons/css/simple-line-icons.css' %}" />

  <link rel="stylesheet" href="{% static 'src/css/vendor/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'src/css/vendor/bootstrap.rtl.only.min.css' %}" />
  <link rel="stylesheet" href="{% static 'src/css/vendor/bootstrap-float-label.min.css' %}" />
  <link rel="stylesheet" href="{% static 'src/css/main.css' %}" />
  <link rel="stylesheet" href="{% static "src/css/dore.light.bluenavy.min.css" %}" />

</head>

<body class="background show-spinner no-footer">
    <div class="fixed-background"></div>
    <main>
        <div class="container">
            <div class="row h-100">
                <div class="col-12 col-md-10 mx-auto my-auto">
                    <div class="card auth-card">
                        <div class="position-relative image-side ">
                            <p class=" text-white h2">MAGIC IS IN THE DETAILS</p>
                            <p class="white mb-0">
                                Please use this form to register.
                                <br>If you are a member, please
                                <a href="{% url 'home:user-login'%}" class="white">login</a>.
                            </p>
                        </div>
                        <div class="form-side">
                            <a href="#">
                                <img src="{% static 'src/logos/Logo3alababak.svg' %}" alt="">
                            </a>
                            <h6 class="mb-4">Register</h6>
                            <form method="post">
                              {% csrf_token %}

                              {% for field in register_form %}
                              <p>
                                {{ field.label_tag }}<br>
                                {{ field }}
                                {% if field.help_text %}
                                <small style="color: grey">{{ field.help_text }}</small>
                                {% endif %}
                                {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                                {% endfor %}
                              </p>
                              {% endfor %}

                              <button type="submit" class="btn btn-primary">Sgin Up</button>
                              <div class="line line-dashed"></div>
                              <p class="text-muted text-center">
                                <small>Already have an account?</small></p>
                              <a href="{% url 'home:user-login'%}" class="btn btn-default btn-block">Sgin In</a>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
  <script src="{% static 'src/js/vendor/jquery-3.3.1.min.js'%}"></script>
  <script src="{% static 'src/js/vendor/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'src/js/dore.script.js'%}"></script>
  <script src="{% static "src/js/dore.script.js" %}"></script>
  <script src="{% static "src/js/scripts.single.theme.js" %}"></script>
</body>

</html>

alababak/templates/side-bar.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<div class="main-menu">
  <div class="scroll">
    <ul class="list-unstyled">
      <li class="color">
        <a href="#dashboard">
          <i class="iconsminds-shop-4"></i>
          <span>Dashboards</span>
        </a>
      </li>
      <li class="color">
        <a href="#accounts">
          <i class="simple-icon-people"></i> Accounts
        </a>
      </li>
      <li class="color">
        <a href="#inventory">
          <i class="iconsminds-box-close"></i> Inventory
        </a>
      </li>
      <li class="color">
        <a href="#locations">
          <i class="iconsminds-location-2"></i> Locations
        </a>
      </li>
      <li class="color">
        <a href="#trans">
          <i class="iconsminds-receipt-4"></i> Transactions
        </a>
      </li>
      <li class="color">
        <a href="#orders">
          <i class="iconsminds-shopping-cart"></i> Orders
        </a>
      </li>
      <li class="color">
        <a href="#">
          <i class="simple-icon-notebook"></i> Reports
        </a>
      </li>
    </ul>
  </div>
</div>

<div class="sub-menu">
  <div class="scroll">
    <ul class="list-unstyled" data-link="dashboard">
      <li class="color">
        <a href="{% url 'home:homepage'%}">
          <i class="simple-icon-rocket"></i> <span class="d-inline-block">Default</span>
        </a>
      </li>
    </ul>
    <ul class="list-unstyled" data-link="accounts">
      <li class="color">
        <a href="#" data-toggle="collapse" data-target="#collapseAuthorization" aria-expanded="true" aria-controls="collapseAuthorization" class="rotate-arrow-icon opacity-50">
          <i class="simple-icon-arrow-down"></i> <span class="d-inline-block">Accounts List</span>
        </a>
        <div id="collapseAuthorization" class="collapse show">
          <ul class="list-unstyled inner-level-menu">
            <li class="color">
              <a href="{% url 'account:list-customers'%}">
                <i class="simple-icon-user-following"></i> <span class="d-inline-block">Customers</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'account:list-suppliers'%}">
                <i class="simple-icon-user-follow"></i> <span class="d-inline-block">Suppliers</span>
              </a>
            </li>
          </ul>
        </div>
      </li>
    </ul>

    <ul class="list-unstyled" data-link="inventory">
      <li class="color">
        <a href="#" data-toggle="collapse" data-target="#collapseForms" aria-expanded="true" aria-controls="collapseForms" class="rotate-arrow-icon opacity-50">
          <i class="simple-icon-arrow-down"></i> <span class="d-inline-block">Products</span>
        </a>
        <div id="collapseForms" class="collapse show">
          <ul class="list-unstyled inner-level-menu">
            <li class="color">
              <a href="{% url 'inventory:list-products'%}">
                <i class="simple-icon-event"></i> <span class="d-inline-block">Products</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'inventory:list-attributes'%}">
                <i class="simple-icon-doc"></i> <span class="d-inline-block">Attributes</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'inventory:list-brands'%}">
                <i class="simple-icon-check"></i> <span class="d-inline-block">Brands</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'inventory:list-categories'%}">
                <i class="simple-icon-magic-wand"></i> <span class="d-inline-block">Categories</span>
              </a>
            </li>
          </ul>
        </div>
      </li>
      <li class="color">
        <a href="{% url 'inventory:list-stokes'%}">
          <i class="simple-icon-screen-desktop"></i>
          <span class="d-inline-block">Stocktaking</span>
        </a>
      </li>
      <li class="color">
        <a href="{% url 'account:list-customers'%}">
          <i class="iconsminds-coins"></i> <span class="d-inline-block">Tax</span>
        </a>
      </li>
      <li class="color">
        <a href="{% url 'inventory:list-uom'%}">
          <i class="simple-icon-calculator"></i> <span class="d-inline-block">UOM</span>
        </a>
      </li>
    </ul>

    <ul class="list-unstyled" data-link="locations">
      <li class="color">
        <a href="#" data-toggle="collapse" data-target="#collapseForms" aria-expanded="true" aria-controls="collapseForms" class="rotate-arrow-icon opacity-50">
          <i class="simple-icon-arrow-down"></i> <span class="d-inline-block">Locations & Warehouses</span>
        </a>
        <div id="collapseForms" class="collapse show">
          <ul class="list-unstyled inner-level-menu">
            <li class="color">
              <a href="{% url 'location:list-locations'%}">
                <i class="iconsminds-home-3"></i> <span class="d-inline-block">Warehouses</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'location:list-locations'%}">
                <i class="iconsminds-home-3"></i> <span class="d-inline-block">Stores</span>
              </a>
            </li>
          </ul>
        </div>
      </li>
    </ul>

    <ul class="list-unstyled" data-link="trans" id="menuTypes">
      <li class="color">
        <a href="#" data-toggle="collapse" data-target="#collapseMenuDetached" aria-expanded="true" aria-controls="collapseMenuDetached" class="rotate-arrow-icon collapsed">
          <i class="simple-icon-arrow-down"></i> <span class="d-inline-block">Transactions</span>
        </a>
        <div id="collapseMenuDetached" class="collapse show">
          <ul class="list-unstyled inner-level-menu">
            <li class="color">
              <a href="{% url 'account:list-customers'%}">
                <i class="iconsminds-arrow-inside"></i> <span class="d-inline-block">Receiving</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'account:list-customers'%}">
                <i class="iconsminds-arrow-loop"></i> <span class="d-inline-block">Return Receiving</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'account:list-customers'%}">
                <i class="iconsminds-arrow-outside"></i> <span class="d-inline-block">Shipping</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'account:list-customers'%}">
                <i class="iconsminds-arrow-loop"></i> <span class="d-inline-block">Return Shipping</span>
              </a>
            </li>
          </ul>
        </div>
      </li>
    </ul>

    <ul class="list-unstyled" data-link="orders">
      <li class="color">
        <a href="#" data-toggle="collapse" data-target="#collapseForms" aria-expanded="true" aria-controls="collapseForms" class="rotate-arrow-icon opacity-50">
          <i class="simple-icon-arrow-down"></i> <span class="d-inline-block">Orders Menu</span>
        </a>
        <div id="collapseForms" class="collapse show">
          <ul class="list-unstyled inner-level-menu">
            <li class="color">
              <a href="{% url 'orders:list-po'%}">
                <i class="iconsminds-add-cart"></i> <span class="d-inline-block">Purchase Orders</span>
              </a>
            </li>
            <li class="color">
              <a href="{% url 'orders:list-so'%}">
                <i class="iconsminds-add-cart"></i> <span class="d-inline-block">Sales Orders</span>
              </a>
            </li>
          </ul>
        </div>
      </li>
    </ul>

  </div>
</div>

alababak/templates/top-nav.html
{% load static %}
{% load i18n %}
{% load l10n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}

<div class="d-flex align-items-center navbar-left">
    <a href="#" class="menu-button d-none d-md-block">
        <svg class="main" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 9 17">
            <rect x="0.48" y="0.5" width="7" height="1" />
            <rect x="0.48" y="7.5" width="7" height="1" />
            <rect x="0.48" y="15.5" width="7" height="1" />
        </svg>
        <svg class="sub" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 17">
            <rect x="1.56" y="0.5" width="16" height="1" />
            <rect x="1.56" y="7.5" width="16" height="1" />
            <rect x="1.56" y="15.5" width="16" height="1" />
        </svg>
    </a>

    <a href="#" class="menu-button-mobile d-xs-block d-sm-block d-md-none">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26 17">
            <rect x="0.5" y="0.5" width="25" height="1" />
            <rect x="0.5" y="7.5" width="25" height="1" />
            <rect x="0.5" y="15.5" width="25" height="1" />
        </svg>
    </a>

</div>


<a class="navbar-logo" href="{% url 'home:homepage'%}">
    <span class="logo d-none d-xs-block"></span>
    <span class="logo-mobile d-block d-xs-none"></span>
</a>

<div class="navbar-right">
    <div class="user d-inline-block">
        <button class="btn btn-empty p-0" type="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <span class="name">{{ request.user|capfirst }}</span>
            <span>
                <img alt="Profile Picture" src="{% static 'src/img/profiles/l-1.jpg' %}" />
            </span>
        </button>

        <div class="dropdown-menu dropdown-menu-right mt-3">
            <!-- <a class="dropdown-item" href="#">Account</a> -->
            <a class="dropdown-item" href="{% url 'home:logout'%}">Sign out</a>
        </div>
    </div>
</div>