alababak/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('account/', include('account.urls')),
                  path('inventory/', include('inventory.urls')),
                  path('orders/', include('orders.urls')),
                  path('locations/', include('location.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from home import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('en/', views.viewEN, name='en'),
    path('ar/', views.viewAR, name='ar'),
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('', views.homepage, name='homepage'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

inventory/urls.py
from django.urls import path
from inventory import views

app_name = 'inventory'
urlpatterns = [
               path('category/list/', views.list_categorires_view, name='list-categories'),
               path('category/create/', views.create_category_view, name='create-category'),
               path('brands/list/', views.list_brands_view, name='list-brands'),
               path('brand/create/', views.create_brand_view, name='create-brand'),
               path('attribute/list/', views.list_attributes_view, name='list-attributes'),
               path('attribute/create/', views.create_attribute_view, name='create-attribute'),
               path('product/list/', views.list_products_view, name='list-products'),
               path('product/create/', views.create_product_item_view, name='create-product'),
               path('stoke/list/', views.list_stoketake_view, name='list-stokes'),
               path('stoke/create/', views.create_stoketake_view, name='create-stoke'),
               path('uom/create/', views.create_uom_view, name='create-uom'),
               path('uom/list/', views.list_uom_view, name='list-uom'),

]

inventory/forms.py
from django import forms
from django.forms import inlineformset_factory, modelformset_factory
from inventory.models import (Category, Brand, Attribute, Uom, Item, Product, StokeTake, StokeEntry, Uom, )


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


category_model_formset = modelformset_factory(Category, form=CategoryForm, extra=3, can_delete=False)


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(BrandForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


brand_model_formset = modelformset_factory(Brand, form=BrandForm, extra=3, can_delete=False)


class AttributeForm(forms.ModelForm):
    class Meta:
        model = Attribute
        fields = '__all__'
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(AttributeForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


attribute_model_formset = modelformset_factory(Attribute, form=AttributeForm, extra=3, can_delete=False)


class UOMForm(forms.ModelForm):
    class Meta:
        model = Uom
        fields = '__all__'
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(UOMForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


uom_formset = modelformset_factory(Uom, form=UOMForm, extra=3, can_delete=False)


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)


product_item_inlineformset = inlineformset_factory(Product, Item, form=ItemForm, extra=3, can_delete=False)


class StokeTakeForm(forms.ModelForm):
    class Meta:
        model = StokeTake
        fields = '__all__'
        exclude = ('company', 'created_at', 'last_updated_at', 'created_by', 'last_updated_by')
        widgets = {
            'date': forms.DateInput(attrs={'class': 'form-control tm', 'type': 'date', })
        }

    def __init__(self, *args, **kwargs):
        super(StokeTakeForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


class StokeEntryForm(forms.ModelForm):
    class Meta:
        model = StokeEntry
        fields = '__all__'
        exclude = ('company', 'approval','created_at', 'last_updated_at', 'created_by', 'last_updated_by')

    def __init__(self, *args, **kwargs):
        super(StokeEntryForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            if self.fields[field].widget.input_type == 'checkbox':
                self.fields[field].widget.attrs['class'] = 'form-check-input'
            else:
                self.fields[field].widget.attrs['class'] = 'form-control'


stoke_entry_formset = inlineformset_factory(StokeTake, StokeEntry, form=StokeEntryForm, extra=3, can_delete=False)

inventory/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from inventory.models import (Category, Brand, Product, Attribute, Item, Uom, StokeTake)
from inventory.forms import (CategoryForm, category_model_formset, BrandForm, brand_model_formset,
                             AttributeForm, attribute_model_formset, ProductForm, product_item_inlineformset,
                             stoke_entry_formset, uom_formset, StokeTakeForm)


def create_category_view(request):
    category_formset = category_model_formset(queryset=Category.objects.none())
    if request.method == 'POST':
        category_formset = category_model_formset(request.POST)
        if category_formset.is_valid():
            category_obj = category_formset.save(commit=False)
            for form in category_obj:
                form.company = request.user.company
                form.created_by = request.user
                form.save()
            return redirect('inventory:list-categories')
    categoryContext = {
        'category_formset': category_formset,
        'title': 'New Category'

    }
    return render(request, 'create-category.html', context=categoryContext)


def list_categorires_view(request):
    categories_list = Category.objects.all()
    categoryContext = {
        'categories_list': categories_list
    }
    return render(request, 'list-categories.html', context=categoryContext)


def list_brands_view(request):
    brands_list = Brand.objects.all()
    brandsContext = {
        'brands_list': brands_list
    }
    return render(request, 'list-brands.html', context=brandsContext)


def create_brand_view(request):
    brand_formset = brand_model_formset(queryset=Brand.objects.none())
    if request.method == 'POST':
        brand_formset = brand_model_formset(request.POST)
        if brand_formset.is_valid():
            brand_obj = brand_formset.save(commit=False)
            for form in brand_obj:
                form.company = request.user.company
                form.created_by = request.user
                form.save()
            return redirect('inventory:list-brands')
    categoryContext = {
        'brand_formset': brand_formset,
        'title': 'New Brand'

    }
    return render(request, 'create-brand.html', context=categoryContext)


def list_attributes_view(request):
    attributes_list = Attribute.objects.all()
    attributesContext = {
        'attributes_list': attributes_list
    }
    return render(request, 'list-attributes.html', context=attributesContext)


def create_attribute_view(request):
    attribute_formset = attribute_model_formset(queryset=Attribute.objects.none())
    if request.method == 'POST':
        attribute_formset = attribute_model_formset(request.POST)
        if attribute_formset.is_valid():
            attribute_obj = attribute_formset.save(commit=False)
            for form in attribute_obj:
                form.company = request.user.company
                form.created_by = request.user
                form.save()
            return redirect('inventory:list-attributes')
    attributeContext = {
        'attribute_formset': attribute_formset,
        'title': 'New Attribute'

    }
    return render(request, 'create-attribute.html', context=attributeContext)


def list_products_view(request):
    products_list = Product.objects.all()
    productsContext = {
        'products_list': products_list
    }
    return render(request, 'list-products.html', context=productsContext)


def create_product_item_view(request):
    product_form = ProductForm()
    item_formset = product_item_inlineformset(queryset=Item.objects.none())
    if request.method == 'POST':
        product_form = ProductForm(request.POST)
        item_formset = product_item_inlineformset(request.POST)
        if product_form.is_valid() and item_formset.is_valid():
            product_obj = product_form.save(commit=False)
            product_obj.company = request.user.company
            product_obj.created_by = request.user
            product_obj.save()
            item_formset = product_item_inlineformset(request.POST, instance=product_obj)
            if item_formset.is_valid():
                item_obj = item_formset.save(commit=False)
                for form in item_obj:
                    form.created_by = request.user
                    form.save()
            return redirect('inventory:list-products')
    attributeContext = {
        'product_form': product_form,
        'item_formset': item_formset,

    }
    return render(request, 'create-product-item.html', context=attributeContext)


def create_stoketake_view(request):
    stoke_from = StokeTakeForm()
    stoke_entry_inlineformset = stoke_entry_formset()
    if request.method == 'POST':
        stoke_form = StokeTakeForm(request.POST)
        stoke_entry_inlineformset = stoke_entry_formset(request.POST)
        if stoke_form.is_valid() and stoke_entry_inlineformset.is_valid():
            stoke_obj = stoke_form.save(commit=False)
            stoke_obj.created_by = request.user
            stoke_obj.company = request.user.company
            stoke_obj.save()
            stoke_entry_inlineformset = stoke_entry_formset(request.POST, instance=stoke_obj)
            if stoke_entry_inlineformset.is_valid():
                stoke_entry_obj = stoke_entry_inlineformset.save(commit=False)
                for stoke_entry in stoke_entry_obj:
                    stoke_entry.created_by = request.user
                    stoke_entry.save()
                return redirect('inventory:list-stokes')
            else:
                print(stoke_entry_inlineformset.errors)
        else:
            print(stoke_form.errors)
    stoke_context = {
        'stoke_form': stoke_from,
        'stoke_entry_inlineformset': stoke_entry_inlineformset,
        'title': 'New Stoke Take'

    }
    return render(request, 'create-stoke.html', context=stoke_context)


def list_stoketake_view(request):
    stoke_list = StokeTake.objects.all()
    stokes_context = {
        'stoke_list': stoke_list
    }
    return render(request, 'list-stokes.html', context=stokes_context)


def create_uom_view(request):
    uom_from = uom_formset(queryset=Uom.objects.none())
    if request.method == 'POST':
        uom_from = uom_formset(request.POST)
        if uom_from.is_valid():
            uom_obj = uom_from.save(commit=False)
            for uom in uom_obj:
                uom.created_by = request.user
                uom.company = request.user.company
                uom.save()
            return redirect("inventory:list-uom")
        else:
            print(uom_from.errors)
    uom_context = {
        'uom_from': uom_from,
        'title': 'New UOM'

    }
    return render(request, 'create-uom.html', context=uom_context)


def list_uom_view(request):
    uom_list = Uom.objects.all()
    uom_context = {
        'uom_list': uom_list
    }
    return render(request, 'list-uom.html', context=uom_context)

inventory/templates/list-attributes.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Attributes</h1>
      <div class="text-zero top-right-button-container">
        <a href="{% url 'inventory:create-attribute'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">{% trans "ADD NEW" %}</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature4 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending">Attribute ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Attribute Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Display Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for attribute in attributes_list %}
                <tr role="row">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ attribute.name }}</td>
                  <td>{{ attribute.display_name }}</td>
                  <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="#">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete-modal{{attribute.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <div class="modal fade" id="delete-modal{{attribute.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="#" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}

inventory/templates/list-brands.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Brands</h1>
      <div class="text-zero top-right-button-container">
        <a href="{% url 'inventory:create-brand'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">{% trans "ADD NEW" %}</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature4 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending">Brand ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Brand Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Description" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for brand in brands_list %}
                <tr role="row">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ brand.name }}</td>
                  <td>{{ brand.description }}</td>
                  <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="#">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete-modal{{brand.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <div class="modal fade" id="delete-modal{{brand.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="#" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}

inventory/templates/list-categories.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Categories</h1>
      <div class="text-zero top-right-button-container">
        <a href="{% url 'inventory:create-category'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">{% trans "ADD NEW" %}</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature5 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending">Category ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Category Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Description" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Parent Category" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for category in categories_list %}
                <tr role="row">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ category.name }}</td>
                  <td>{{ category.description }}</td>
                  <td>{{ category.parent_category }}</td>
                  <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="#">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete-modal{{category.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <div class="modal fade" id="delete-modal{{category.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="#" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}

inventory/templates/list-products.html
{% extends 'master.html' %}
{% load static %}
{% load l10n %}
{% load i18n %}

{% block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h1>Products</h1>
      <div class="text-zero top-right-button-container">
        <a href="{% url 'inventory:create-product'%}"><button type="button" class="btn btn-primary btn-lg top-right-button mr-1">{% trans "ADD NEW" %}</button></a>
      </div>
      <div class="separator mb-5"></div>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4 no-footer">
            <div class="row view-filter">
              <div class="col-sm-12">
              </div>
            </div>
            <table class="data-table data-table-feature6 dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
              <thead>
                <tr role="row">
                  <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending">Product ID</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Brand Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Category Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Product Name" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Discription" %}</th>
                  <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1">{% trans "Actions" %}</th>
                </tr>
              </thead>
              <tbody>
                {% for product in products_list %}
                <tr role="row">
                  <td class="sorting_1">{{ forloop.counter }}</td>
                  <td>{{ product.brand }}</td>
                  <td>{{ product.category }}</td>
                  <td>{{ product.name }}</td>
                  <td>{{ product.description }}</td>
                  <td>
                    <div class="dropdown d-inline-block">
                      <a class="btn btn-outline-primary dropdown-toggle mb-1" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Actions
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" x-placement="top-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, -2px, 0px);">
                        <a class="dropdown-item" href="#">{% trans "Update" %}</a>
                        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#delete-modal{{product.pk}}">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </td>
                </tr>
                <div class="modal fade" id="delete-modal{{product.pk}}" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-body">
                        <p>{% trans "Are you sure you want to delete this record?" %}</p>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans "No" %}</button>
                        <a href="#" class="btn btn-danger" type="button">{% trans "Delete" %}</a>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body%}